[
    {"delete": {"status": {"user_id_str":"262554766",
                           "id_str":"166881788990472193",
                           "id":166881788990472193,
                           "user_id":262554766}}},
    {"retweeted":false,
     "text":"Mamatao http:\/\/t.co\/Xd2h86JK",
     "entities":{"urls":[{"indices":[9, 29],
                          "display_url":"colfersaurusrex.tumblr.com\/post\/266586435\u2026",
                          "expanded_url":"http:\/\/colfersaurusrex.tumblr.com\/post\/26658643574",
                          "url":"http:\/\/t.co\/Xd2h86JK"}],
                 "hashtags":[],
                 "user_mentions":[]},
     "retweet_count":0,
     "source":"web", 
     "id":237975199826472960,    
     "user":{"statuses_count":23824,
             "profile_background_image_url":"http:\/\/a0.twimg.com\/profile_background_images\/544219983\/Musicals.jpg",
             "time_zone":"Helsinki",
             "friends_count":261,
             "location":"",
             "listed_count":3,
             "geo_enabled":false,
             "profile_link_color":"FF0000",
             "screen_name":"NymeriaSutcliff",
             "verified":false,
             "followers_count":141,
             "default_profile":false,
             "lang":"en"}
    },
    {"retweeted":false,
     "text":"Sipping on purple",    
     "entities":{"urls":[],
                 "hashtags":[],
                 "user_mentions":[]},
     "retweet_count":0,
     "source":"\u003Ca href=\"http:\/\/twitter.com\/devices\" rel=\"nofollow\"\u003Etxt\u003C\/a\u003E",
     "user":{"statuses_count":4983,
             "profile_background_image_url":"http:\/\/a0.twimg.com\/profile_background_images\/442238941\/derrick-rose.jpg",
             "time_zone":null,
             "friends_count":738,
             "location":"",
             "listed_count":0,
             "geo_enabled":false,
             "profile_link_color":"0084B4",
             "screen_name":"ron_justdoit",
             "verified":false,
             "followers_count":725,
             "default_profile":false,
             "lang":"en"},
     "id":237975199809667072},
    {"retweeted":false,
     "text":"#topreview #Review New - Review Engine R O I - Facebook Review App: This Innovative Fan Reviews Facebook App And... http:\/\/t.co\/NBD1To8j",
     "entities":{"urls":[{"indices":[116,
                                     136],
                          "display_url":"bit.ly\/QmWqrb",
                          "expanded_url":"http:\/\/bit.ly\/QmWqrb",
                          "url":"http:\/\/t.co\/NBD1To8j"}],
                 "hashtags":[{"text":"topreview",
                              "indices":[0,
                                         10]},
                             {"text":"Review",
                              "indices":[11,
                                         18]}],
                 "user_mentions":[]},
     "retweet_count":0,
     "source":"\u003Ca href=\"http:\/\/twitterfeed.com\" rel=\"nofollow\"\u003Etwitterfeed\u003C\/a\u003E",     
     "user":{"statuses_count":5296,
             "profile_background_image_url":"http:\/\/a0.twimg.com\/profile_background_images\/587674528\/4jd244b1tr38ey0twocl.jpeg",
             "time_zone":"Bangkok",
             "friends_count":9,
             "location":"",
             "default_profile":false,
             "lang":"en"},
     "id":237975199843250178
    },
    {"retweeted":false,
     "text":"SO excited that I'm gonna be a Tia again! \ud83d\ude0a",     
     "entities":{"urls":[],
                 "hashtags":[],
                 "user_mentions":[]},
     "source":"\u003Ca href=\"http:\/\/twitter.com\/download\/iphone\" rel=\"nofollow\"\u003ETwitter for iPhone\u003C\/a\u003E",     
     "user":{"statuses_count":9960,
             "profile_background_image_url":"http:\/\/a0.twimg.com\/profile_background_images\/60659599\/background.png",
             "time_zone":"Mountain Time (US & Canada)",
             "friends_count":461,
             "location":"",
             "default_profile":false,
             "lang":"en"},
     "id":237975199822258176
    }
]
